export const ADD_TASK = 'addTask';
export const GET_INITIAL_SPRINT = 'GET_INITIAL_SPRINT';
export const GET_INITIAL_SPRINT_SUCCESS = 'GET_INITIAL_SPRINT_SUCCESS';
export const GET_INITIAL_SPRINT_FAILURE = 'GET_INITIAL_SPRINT_FAILURE';